version: 0.2

env:
  variables:
    STACK_NAME: "national_council_backend"
    ENVIRONMENT: "production"
    GITHUB_REPO_URL: "https://github.com/ASUCICREPO/NCMW-Learning-Navigator-chatbot"
    GITHUB_OWNER: "ASUCICREPO"
    GITHUB_REPO: "NCMW-Learning-Navigator-chatbot"
  parameter-store:
    ADMIN_EMAIL: "/learning-navigator/admin-email"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - echo "=========================================="
      - echo "Learning Navigator - Full Stack Deployment"
      - echo "=========================================="
      - echo "Installation phase started on `date`"
      - echo "AWS Account ID - $AWS_ACCOUNT_ID"
      - echo "AWS Region - $AWS_DEFAULT_REGION"
      - echo "Environment - $ENVIRONMENT"
      - npm install -g aws-cdk@latest typescript @aws-amplify/cli
      - pip install --upgrade awscli
      - yum install -y git || apt-get install -y git || true

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Validating AWS credentials..."
      - aws sts get-caller-identity
      - test -n "$ADMIN_EMAIL" || (echo "ERROR - ADMIN_EMAIL parameter not found" && exit 1)
      - echo "GitHub Repository - $GITHUB_REPO_URL"
      - echo "Admin Email - $ADMIN_EMAIL"

  build:
    commands:
      - echo "=========================================="
      - echo "PHASE 1 - Backend Deployment (CDK)"
      - echo "=========================================="
      - echo "Build phase started on `date`"
      - pwd
      - ls -la
      - cd $CODEBUILD_SRC_DIR/cdk_backend
      - echo "Installing backend dependencies..."
      - npm install
      - echo "Synthesizing CDK stack..."
      - cdk synth
      - echo "Bootstrapping CDK (if needed)..."
      - cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION || true
      - echo "Deploying CDK stack..."
      - cdk deploy --context environment=$ENVIRONMENT --context githubOwner=$GITHUB_OWNER --context githubRepo=$GITHUB_REPO --context adminEmail=$ADMIN_EMAIL --require-approval never --outputs-file outputs.json
      - echo "Backend deployment completed!"
      - cat outputs.json
      - cd $CODEBUILD_SRC_DIR
      - cp cdk_backend/outputs.json ./outputs.json
      - echo "Extracting API endpoints..."
      - export WEBSOCKET_URL=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['WebSocketURL']||''")
      - export API_GATEWAY_URL=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['RestAPIURL']||''")
      - export USER_POOL_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['UserPoolId']||''")
      - export USER_POOL_CLIENT_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['UserPoolClientId']||''")
      - export AMPLIFY_APP_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['AmplifyAppId']||''")
      - echo "API Endpoints extracted"
      - echo "  WebSocket URL - $WEBSOCKET_URL"
      - echo "  API Gateway URL - $API_GATEWAY_URL"
      - echo "  User Pool ID - $USER_POOL_ID"
      - echo "  Amplify App ID - $AMPLIFY_APP_ID"
      - echo "=========================================="
      - echo "PHASE 2 - Frontend Build"
      - echo "=========================================="
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo "Creating production environment configuration..."
      - echo "REACT_APP_ENV=production" > .env.production
      - echo "REACT_APP_API_ENDPOINT=$API_GATEWAY_URL" >> .env.production
      - echo "REACT_APP_WS_ENDPOINT=$WEBSOCKET_URL" >> .env.production
      - echo "REACT_APP_FEEDBACK_API=$API_GATEWAY_URL/feedback" >> .env.production
      - echo "REACT_APP_COGNITO_USER_POOL_ID=$USER_POOL_ID" >> .env.production
      - echo "REACT_APP_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.production
      - echo "REACT_APP_COGNITO_REGION=$AWS_DEFAULT_REGION" >> .env.production
      - echo "REACT_APP_ALLOW_FILE_UPLOAD=false" >> .env.production
      - echo "REACT_APP_ALLOW_MARKDOWN_BOT=true" >> .env.production
      - echo "REACT_APP_ENABLE_SPEECH_RECOGNITION=true" >> .env.production
      - echo "GENERATE_SOURCEMAP=false" >> .env.production
      - echo "INLINE_RUNTIME_CHUNK=false" >> .env.production
      - echo "REACT_APP_LOG_LEVEL=error" >> .env.production
      - echo "Environment configuration created"
      - cat .env.production
      - echo "Installing frontend dependencies..."
      - npm ci --production=false
      - echo "Building production bundle..."
      - npm run build
      - echo "Build completed. Size analysis"
      - du -sh build/
      - du -h build/static/js/*.js 2>/dev/null | sort -h | head -10 || true

  post_build:
    commands:
      - echo "=========================================="
      - echo "PHASE 3 - Deploying to Amplify"
      - echo "=========================================="
      - echo "Post-build phase started on `date`"
      - pwd
      - ls -la
      - cd $CODEBUILD_SRC_DIR/frontend
      - test -n "$AMPLIFY_APP_ID" || (echo "ERROR - No Amplify App ID found" && exit 1)
      - echo "Deploying to Amplify App - $AMPLIFY_APP_ID"
      - cd build
      - zip -q -r ../build.zip .
      - cd ..
      - aws amplify create-deployment --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION > deployment.json
      - export UPLOAD_URL=$(node -p "require('./deployment.json').zipUploadUrl")
      - curl -H "Content-Type application/zip" "$UPLOAD_URL" --upload-file build.zip
      - export JOB_ID=$(node -p "require('./deployment.json').jobId")
      - aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION
      - echo "Deployment started. Job ID - $JOB_ID"
      - echo "Waiting for deployment to complete..."
      - |
        for i in {1..60}; do
          STATUS=$(aws amplify get-job --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION --query 'job.summary.status' --output text)
          echo "[$i/60] Deployment status - $STATUS"
          if [ "$STATUS" = "SUCCEED" ]; then
            echo "Deployment completed successfully!"
            break
          elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELLED" ]; then
            echo "ERROR - Deployment failed with status $STATUS"
            exit 1
          fi
          sleep 10
        done
      - export AMPLIFY_URL=$(aws amplify get-app --app-id $AMPLIFY_APP_ID --region $AWS_DEFAULT_REGION --query 'app.defaultDomain' --output text)
      - echo "=========================================="
      - echo "DEPLOYMENT SUCCESSFUL!"
      - echo "=========================================="
      - echo "Application URL - https://main.$AMPLIFY_URL"
      - echo "Admin Portal - https://main.$AMPLIFY_URL/admin"
      - echo "WebSocket - $WEBSOCKET_URL"
      - echo "REST API - $API_GATEWAY_URL"
      - echo "Admin Email - $ADMIN_EMAIL"
      - echo "=========================================="
      - cd $CODEBUILD_SRC_DIR
      - echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"environment\":\"$ENVIRONMENT\",\"amplify_url\":\"https://main.$AMPLIFY_URL\",\"websocket_url\":\"$WEBSOCKET_URL\",\"api_gateway_url\":\"$API_GATEWAY_URL\",\"user_pool_id\":\"$USER_POOL_ID\",\"admin_email\":\"$ADMIN_EMAIL\"}" > deployment-info.json
      - cat deployment-info.json
      - echo "Deployment pipeline completed successfully!"

artifacts:
  files:
    - outputs.json
    - deployment-info.json
    - frontend/build/**/*
  name: full-stack-deployment

cache:
  paths:
    - 'cdk_backend/node_modules/**/*'
    - 'frontend/node_modules/**/*'
