version: 0.2

# Main Deployment Pipeline - Orchestrates backend and frontend deployment
# Clones repo and deploys backend first, captures outputs, then deploys frontend to Amplify

env:
  variables:
    STACK_NAME: "national_council_backend"
    ENVIRONMENT: "production"
    GITHUB_REPO_URL: "https://github.com/OWNER/REPO.git"  # Will be set dynamically
  parameter-store:
    GITHUB_OWNER: "/learning-navigator/github-owner"
    GITHUB_REPO: "/learning-navigator/github-repo"
    ADMIN_EMAIL: "/learning-navigator/admin-email"
    # Optional: GitHub token for private repos
    # GITHUB_TOKEN: "/learning-navigator/github-token"

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.12
    commands:
      - echo "=========================================="
      - echo "Learning Navigator - Full Stack Deployment"
      - echo "=========================================="
      - echo "Installation phase started on `date`"
      - echo "AWS Account ID - $AWS_ACCOUNT_ID"
      - echo "AWS Region - $AWS_DEFAULT_REGION"
      - echo "Environment - $ENVIRONMENT"

      # Install global dependencies
      - npm install -g aws-cdk@latest typescript @aws-amplify/cli
      - pip install --upgrade awscli

      # Install git (usually pre-installed in CodeBuild)
      - yum install -y git || apt-get install -y git || true

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"

      # Validate AWS credentials
      - echo "Validating AWS credentials..."
      - aws sts get-caller-identity

      # Validate required environment variables
      - |
        if [ -z "$GITHUB_OWNER" ] || [ -z "$GITHUB_REPO" ] || [ -z "$ADMIN_EMAIL" ]; then
          echo "ERROR: Required parameters not found!"
          echo "Please set the following in Parameter Store:"
          echo "  - /learning-navigator/github-owner"
          echo "  - /learning-navigator/github-repo"
          echo "  - /learning-navigator/admin-email"
          exit 1
        fi

      - echo "GitHub Repository: $GITHUB_OWNER/$GITHUB_REPO"
      - echo "Admin Email: $ADMIN_EMAIL"

  build:
    commands:
      - echo "=========================================="
      - echo "PHASE 1: Backend Deployment (CDK)"
      - echo "=========================================="
      - echo "Build phase started on `date`"

      # Deploy backend using CDK
      - cd cdk_backend
      - echo "Installing backend dependencies..."
      - npm install

      - echo "Synthesizing CDK stack..."
      - cdk synth

      - echo "Bootstrapping CDK (if needed)..."
      - cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION || true

      - echo "Deploying CDK stack..."
      - |
        cdk deploy \
          --context environment=$ENVIRONMENT \
          --context githubOwner=$GITHUB_OWNER \
          --context githubRepo=$GITHUB_REPO \
          --context adminEmail=$ADMIN_EMAIL \
          --require-approval never \
          --outputs-file outputs.json

      - echo "Backend deployment completed!"
      - cat outputs.json

      # Extract outputs
      - cd ..
      - cp cdk_backend/outputs.json ./outputs.json

      - echo "Extracting API endpoints..."
      - |
        export WEBSOCKET_URL=$(node -p "
          const outputs = require('./outputs.json');
          const stack = Object.keys(outputs)[0];
          outputs[stack]['WebSocketURL'] || ''
        ")
      - |
        export API_GATEWAY_URL=$(node -p "
          const outputs = require('./outputs.json');
          const stack = Object.keys(outputs)[0];
          outputs[stack]['RestAPIURL'] || ''
        ")
      - |
        export USER_POOL_ID=$(node -p "
          const outputs = require('./outputs.json');
          const stack = Object.keys(outputs)[0];
          outputs[stack]['UserPoolId'] || ''
        ")
      - |
        export USER_POOL_CLIENT_ID=$(node -p "
          const outputs = require('./outputs.json');
          const stack = Object.keys(outputs)[0];
          outputs[stack]['UserPoolClientId'] || ''
        ")
      - |
        export AMPLIFY_APP_ID=$(node -p "
          const outputs = require('./outputs.json');
          const stack = Object.keys(outputs)[0];
          outputs[stack]['AmplifyAppId'] || ''
        ")

      - echo "API Endpoints extracted:"
      - echo "  WebSocket URL: $WEBSOCKET_URL"
      - echo "  API Gateway URL: $API_GATEWAY_URL"
      - echo "  User Pool ID: $USER_POOL_ID"
      - echo "  Amplify App ID: $AMPLIFY_APP_ID"

      - echo "=========================================="
      - echo "PHASE 2: Frontend Build"
      - echo "=========================================="

      # Create production environment file
      - cd frontend
      - echo "Creating production environment configuration..."
      - |
        cat > .env.production << EOF
        # Auto-generated by CodeBuild on $(date)
        REACT_APP_ENV=production

        # API Endpoints
        REACT_APP_API_ENDPOINT=$API_GATEWAY_URL
        REACT_APP_WS_ENDPOINT=$WEBSOCKET_URL
        REACT_APP_FEEDBACK_API=$API_GATEWAY_URL/feedback

        # AWS Cognito Configuration
        REACT_APP_COGNITO_USER_POOL_ID=$USER_POOL_ID
        REACT_APP_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID
        REACT_APP_COGNITO_REGION=$AWS_DEFAULT_REGION

        # Feature Flags
        REACT_APP_ALLOW_FILE_UPLOAD=false
        REACT_APP_ALLOW_MARKDOWN_BOT=true
        REACT_APP_ENABLE_SPEECH_RECOGNITION=true

        # Build Configuration
        GENERATE_SOURCEMAP=false
        INLINE_RUNTIME_CHUNK=false

        # Logging
        REACT_APP_LOG_LEVEL=error

        # Version
        REACT_APP_VERSION=\$npm_package_version
        EOF

      - echo "Environment configuration created:"
      - cat .env.production

      # Install and build frontend
      - echo "Installing frontend dependencies..."
      - npm ci --production=false

      - echo "Building production bundle..."
      - npm run build

      - echo "Build completed. Size analysis:"
      - du -sh build/
      - du -h build/static/js/*.js 2>/dev/null | sort -h | head -10 || true

  post_build:
    commands:
      - echo "=========================================="
      - echo "PHASE 3: Deploying to Amplify"
      - echo "=========================================="
      - echo "Post-build phase started on `date`"

      - cd frontend

      # Deploy to Amplify
      - |
        if [ ! -z "$AMPLIFY_APP_ID" ]; then
          echo "Deploying to Amplify App: $AMPLIFY_APP_ID"

          # Create deployment
          cd build
          zip -q -r ../build.zip .
          cd ..

          # Create Amplify deployment
          aws amplify create-deployment \
            --app-id $AMPLIFY_APP_ID \
            --branch-name main \
            --region $AWS_DEFAULT_REGION > deployment.json

          # Upload build
          export UPLOAD_URL=$(node -p "require('./deployment.json').zipUploadUrl")
          curl -H "Content-Type: application/zip" "$UPLOAD_URL" --upload-file build.zip

          # Start deployment
          export JOB_ID=$(node -p "require('./deployment.json').jobId")
          aws amplify start-deployment \
            --app-id $AMPLIFY_APP_ID \
            --branch-name main \
            --job-id $JOB_ID \
            --region $AWS_DEFAULT_REGION

          echo "Deployment started. Job ID: $JOB_ID"

          # Wait for deployment
          echo "Waiting for deployment to complete..."
          for i in {1..60}; do
            STATUS=$(aws amplify get-job \
              --app-id $AMPLIFY_APP_ID \
              --branch-name main \
              --job-id $JOB_ID \
              --region $AWS_DEFAULT_REGION \
              --query 'job.summary.status' \
              --output text)

            echo "[$i/60] Deployment status: $STATUS"

            if [ "$STATUS" = "SUCCEED" ]; then
              echo "Deployment completed successfully!"
              break
            elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELLED" ]; then
              echo "ERROR: Deployment failed with status: $STATUS"
              exit 1
            fi

            sleep 10
          done

          # Get Amplify URL
          export AMPLIFY_URL=$(aws amplify get-app \
            --app-id $AMPLIFY_APP_ID \
            --region $AWS_DEFAULT_REGION \
            --query 'app.defaultDomain' \
            --output text)

          echo ""
          echo "=========================================="
          echo "âœ… DEPLOYMENT SUCCESSFUL!"
          echo "=========================================="
          echo ""
          echo "ðŸŒ Application URL:"
          echo "   https://main.$AMPLIFY_URL"
          echo ""
          echo "ðŸ“Š Admin Dashboard:"
          echo "   https://main.$AMPLIFY_URL/admin"
          echo ""
          echo "ðŸ”— Backend APIs:"
          echo "   WebSocket: $WEBSOCKET_URL"
          echo "   REST API: $API_GATEWAY_URL"
          echo ""
          echo "ðŸ‘¤ Admin Login:"
          echo "   Email: $ADMIN_EMAIL"
          echo "   (Check email for temporary password)"
          echo ""
          echo "=========================================="

          # Save deployment info
          cat > ../deployment-info.json << EOF
          {
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "environment": "$ENVIRONMENT",
            "amplify_url": "https://main.$AMPLIFY_URL",
            "websocket_url": "$WEBSOCKET_URL",
            "api_gateway_url": "$API_GATEWAY_URL",
            "user_pool_id": "$USER_POOL_ID",
            "admin_email": "$ADMIN_EMAIL"
          }
          EOF

          cat ../deployment-info.json

        else
          echo "ERROR: No Amplify App ID found in CDK outputs"
          echo "Please ensure Amplify app is created in CDK stack"
          exit 1
        fi

      - echo "Deployment pipeline completed successfully!"

artifacts:
  files:
    - outputs.json
    - deployment-info.json
    - frontend/build/**/*
  name: full-stack-deployment

cache:
  paths:
    - 'cdk_backend/node_modules/**/*'
    - 'frontend/node_modules/**/*'

reports:
  deployment-report:
    files:
      - 'deployment-info.json'
    file-format: 'JSON'