version: 0.2

env:
  variables:
    STACK_NAME: "national_council_backend"
    ENVIRONMENT: "production"
    GITHUB_REPO_URL: "https://github.com/ASUCICREPO/NCMW-Learning-Navigator-chatbot"
    GITHUB_OWNER: "ASUCICREPO"
    GITHUB_REPO: "NCMW-Learning-Navigator-chatbot"
  parameter-store:
    ADMIN_EMAIL: "/learning-navigator/admin-email"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - echo "=========================================="
      - echo "Learning Navigator - Full Stack Deployment"
      - echo "=========================================="
      - echo "Installation phase started on `date`"
      - echo "AWS Account ID - $AWS_ACCOUNT_ID"
      - echo "AWS Region - $AWS_DEFAULT_REGION"
      - echo "Environment - $ENVIRONMENT"
      - npm install -g aws-cdk@latest typescript @aws-amplify/cli
      - pip install --upgrade awscli
      - yum install -y git || apt-get install -y git || true

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Validating AWS credentials..."
      - aws sts get-caller-identity
      - test -n "$ADMIN_EMAIL" || (echo "ERROR - ADMIN_EMAIL parameter not found" && exit 1)
      - echo "GitHub Repository - $GITHUB_REPO_URL"
      - echo "Admin Email - $ADMIN_EMAIL"

  build:
    commands:
      - echo "=========================================="
      - echo "PHASE 1 - Backend Deployment (CDK)"
      - echo "=========================================="
      - echo "Build phase started on `date`"
      - pwd
      - ls -la
      - cd $CODEBUILD_SRC_DIR/cdk_backend
      - echo "Installing backend dependencies..."
      - npm install
      - echo "Synthesizing CDK stack..."
      - cdk synth --context environment=$ENVIRONMENT --context githubOwner=$GITHUB_OWNER --context githubRepo=$GITHUB_REPO --context adminEmail=$ADMIN_EMAIL
      - echo "Bootstrapping CDK (if needed)..."
      - cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION || true
      - echo "Deploying CDK stack..."
      - cdk deploy --context environment=$ENVIRONMENT --context githubOwner=$GITHUB_OWNER --context githubRepo=$GITHUB_REPO --context adminEmail=$ADMIN_EMAIL --require-approval never --outputs-file outputs.json
      - echo "Backend deployment completed!"
      - cat outputs.json
      - cd $CODEBUILD_SRC_DIR
      - cp cdk_backend/outputs.json ./outputs.json
      - echo "Extracting API endpoints and configuration..."
      - export WEBSOCKET_URL=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['WebSocketURL']||'Not found'")
      - export API_GATEWAY_URL=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['RestAPIURL']||'Not found'")
      - export USER_POOL_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['UserPoolId']||'Not found'")
      - export USER_POOL_CLIENT_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['UserPoolClientId']||'Not found'")
      - export IDENTITY_POOL_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['IdentityPoolId']||'Not found'")
      - export KB_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['KnowledgeBaseId']||'Not found'")
      - export DATA_SOURCE_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['DataSourceId']||'Not found'")
      - export KB_BUCKET=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['KnowledgeBaseBucket']||'Not found'")
      - export AGENT_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['AgentId']||'Not found'")
      - export AGENT_ALIAS_ID=$(node -p "const o=require('./outputs.json'); const s=Object.keys(o)[0]; o[s]['AgentAliasId']||'Not found'")
      - echo "Configuration extracted successfully"
      - echo "  WebSocket URL - $WEBSOCKET_URL"
      - echo "  API Gateway URL - $API_GATEWAY_URL"
      - echo "  User Pool ID - $USER_POOL_ID"
      - echo "  Knowledge Base ID - $KB_ID"
      - echo "  KB Bucket - $KB_BUCKET"
      - echo "=========================================="
      - echo "PHASE 2 - Frontend Build"
      - echo "=========================================="
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo "Creating production environment configuration..."
      - echo "REACT_APP_ENV=production" > .env.production
      - echo "REACT_APP_API_ENDPOINT=$API_GATEWAY_URL" >> .env.production
      - echo "REACT_APP_WS_ENDPOINT=$WEBSOCKET_URL" >> .env.production
      - echo "REACT_APP_FEEDBACK_API=$API_GATEWAY_URL/feedback" >> .env.production
      - echo "REACT_APP_COGNITO_USER_POOL_ID=$USER_POOL_ID" >> .env.production
      - echo "REACT_APP_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.production
      - echo "REACT_APP_COGNITO_REGION=$AWS_DEFAULT_REGION" >> .env.production
      - echo "REACT_APP_ALLOW_FILE_UPLOAD=false" >> .env.production
      - echo "REACT_APP_ALLOW_MARKDOWN_BOT=true" >> .env.production
      - echo "REACT_APP_ENABLE_SPEECH_RECOGNITION=true" >> .env.production
      - echo "GENERATE_SOURCEMAP=false" >> .env.production
      - echo "INLINE_RUNTIME_CHUNK=false" >> .env.production
      - echo "REACT_APP_LOG_LEVEL=error" >> .env.production
      - echo "Environment configuration created"
      - cat .env.production
      - echo "Installing frontend dependencies..."
      - npm ci --production=false
      - echo "Building production bundle..."
      - npm run build
      - echo "Build completed. Size analysis"
      - du -sh build/
      - du -h build/static/js/*.js 2>/dev/null | sort -h | head -10 || true

  post_build:
    commands:
      - echo "=========================================="
      - echo "PHASE 3 - Deploying to Amplify"
      - echo "=========================================="
      - echo "Post-build phase started on `date`"
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo "Checking for existing Amplify app..."
      - |
        AMPLIFY_APP_ID=$(aws amplify list-apps --region $AWS_DEFAULT_REGION --query "apps[?name=='LearningNavigatorUI'].appId | [0]" --output text 2>/dev/null || echo "")
        if [ "$AMPLIFY_APP_ID" = "None" ] || [ -z "$AMPLIFY_APP_ID" ]; then
          echo "Creating new Amplify app..."
          AMPLIFY_APP_ID=$(aws amplify create-app \
            --name LearningNavigatorUI \
            --region $AWS_DEFAULT_REGION \
            --platform WEB \
            --query 'app.appId' \
            --output text)
          echo "Created Amplify App ID - $AMPLIFY_APP_ID"
        else
          echo "Using existing Amplify App ID - $AMPLIFY_APP_ID"
        fi
      - echo "Deploying to Amplify App - $AMPLIFY_APP_ID"
      - echo "Listing all existing branches..."
      - aws amplify list-branches --app-id $AMPLIFY_APP_ID --region $AWS_DEFAULT_REGION || echo "Failed to list branches"
      - |
        set -e
        echo "Checking if main branch exists..."
        echo "App ID: $AMPLIFY_APP_ID"
        echo "Region: $AWS_DEFAULT_REGION"

        BRANCH_EXISTS=$(aws amplify list-branches --app-id $AMPLIFY_APP_ID --region $AWS_DEFAULT_REGION --query "branches[?branchName=='main'].branchName | [0]" --output text 2>&1 || echo "")
        echo "Branch check result: '$BRANCH_EXISTS'"

        if [ "$BRANCH_EXISTS" = "None" ] || [ -z "$BRANCH_EXISTS" ] || [ "$BRANCH_EXISTS" = "null" ]; then
          echo "Branch does not exist. Creating main branch..."
          if aws amplify create-branch \
            --app-id $AMPLIFY_APP_ID \
            --branch-name main \
            --region $AWS_DEFAULT_REGION \
            --no-enable-auto-build \
            --stage PRODUCTION; then
            echo "Branch 'main' created successfully"
            sleep 5
            aws amplify get-branch --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION
          else
            echo "ERROR: Failed to create branch main"
            exit 1
          fi
        else
          echo "Branch 'main' already exists"
          aws amplify get-branch --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION
        fi
      - cd build
      - zip -q -r ../build.zip .
      - cd ..
      - echo "Creating deployment for branch main..."
      - |
        if ! aws amplify create-deployment --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION > deployment.json 2>&1; then
          echo "ERROR: Failed to create deployment. Output:"
          cat deployment.json || echo "No deployment.json file created"
          exit 1
        fi
      - echo "Deployment created successfully"
      - cat deployment.json
      - export UPLOAD_URL=$(node -p "require('./deployment.json').zipUploadUrl")
      - curl -H "Content-Type application/zip" "$UPLOAD_URL" --upload-file build.zip
      - export JOB_ID=$(node -p "require('./deployment.json').jobId")
      - aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION
      - echo "Deployment started. Job ID - $JOB_ID"
      - echo "Waiting for deployment to complete..."
      - |
        for i in {1..60}; do
          STATUS=$(aws amplify get-job --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION --query 'job.summary.status' --output text)
          echo "[$i/60] Deployment status - $STATUS"
          if [ "$STATUS" = "SUCCEED" ]; then
            echo "Deployment completed successfully!"
            break
          elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELLED" ]; then
            echo "ERROR - Deployment failed with status $STATUS"
            exit 1
          fi
          sleep 10
        done
      - export AMPLIFY_URL=$(aws amplify get-app --app-id $AMPLIFY_APP_ID --region $AWS_DEFAULT_REGION --query 'app.defaultDomain' --output text)
      - echo "=========================================="
      - echo "DEPLOYMENT SUCCESSFUL!"
      - echo "=========================================="
      - echo ""
      - echo "ðŸŒ Application URLs:"
      - echo "   Frontend: https://main.$AMPLIFY_URL"
      - echo "   Admin Portal: https://main.$AMPLIFY_URL/admin-dashboard"
      - echo ""
      - echo "ðŸ”Œ API Endpoints:"
      - echo "   WebSocket: $WEBSOCKET_URL"
      - echo "   REST API: $API_GATEWAY_URL"
      - echo ""
      - echo "ðŸ‘¤ Cognito Configuration:"
      - echo "   User Pool ID: $USER_POOL_ID"
      - echo "   User Pool Client ID: $USER_POOL_CLIENT_ID"
      - echo "   Identity Pool ID: $IDENTITY_POOL_ID"
      - echo ""
      - echo "ðŸ¤– Bedrock Agent:"
      - echo "   Agent ID: $AGENT_ID"
      - echo "   Agent Alias ID: $AGENT_ALIAS_ID"
      - echo ""
      - echo "ðŸ“š Knowledge Base:"
      - echo "   KB ID: $KB_ID"
      - echo "   Data Source ID: $DATA_SOURCE_ID"
      - echo "   S3 Bucket: $KB_BUCKET"
      - echo ""
      - echo "ðŸ“§ Admin Configuration:"
      - echo "   Admin Email: $ADMIN_EMAIL"
      - echo ""
      - echo "=========================================="
      - echo "Next Steps:"
      - echo "=========================================="
      - echo ""
      - echo "1. Upload documents to Knowledge Base:"
      - echo "   aws s3 sync ./your-documents/ s3://$KB_BUCKET/pdfs/"
      - echo ""
      - echo "2. Sync Knowledge Base:"
      - echo "   aws bedrock-agent start-ingestion-job \\"
      - echo "     --knowledge-base-id $KB_ID \\"
      - echo "     --data-source-id $DATA_SOURCE_ID \\"
      - echo "     --region $AWS_DEFAULT_REGION"
      - echo ""
      - echo "3. Create admin user:"
      - echo "   aws cognito-idp admin-create-user \\"
      - echo "     --user-pool-id $USER_POOL_ID \\"
      - echo "     --username $ADMIN_EMAIL \\"
      - echo "     --temporary-password 'TempPass123!' \\"
      - echo "     --region $AWS_DEFAULT_REGION"
      - echo ""
      - echo "4. Access your application:"
      - echo "   https://main.$AMPLIFY_URL"
      - echo ""
      - echo "=========================================="
      - cd $CODEBUILD_SRC_DIR
      - |
        cat > deployment-info.json <<EOF
        {
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "environment": "$ENVIRONMENT",
          "frontend_url": "https://main.$AMPLIFY_URL",
          "admin_portal_url": "https://main.$AMPLIFY_URL/admin-dashboard",
          "websocket_url": "$WEBSOCKET_URL",
          "api_gateway_url": "$API_GATEWAY_URL",
          "user_pool_id": "$USER_POOL_ID",
          "user_pool_client_id": "$USER_POOL_CLIENT_ID",
          "identity_pool_id": "$IDENTITY_POOL_ID",
          "agent_id": "$AGENT_ID",
          "agent_alias_id": "$AGENT_ALIAS_ID",
          "knowledge_base_id": "$KB_ID",
          "data_source_id": "$DATA_SOURCE_ID",
          "kb_bucket": "$KB_BUCKET",
          "admin_email": "$ADMIN_EMAIL",
          "region": "$AWS_DEFAULT_REGION"
        }
        EOF
      - cat deployment-info.json
      - echo ""
      - echo "âœ… Deployment pipeline completed successfully! ðŸŽ‰"

artifacts:
  files:
    - outputs.json
    - deployment-info.json
    - frontend/build/**/*
  name: full-stack-deployment

cache:
  paths:
    - 'cdk_backend/node_modules/**/*'
    - 'frontend/node_modules/**/*'
